raphael: Add CustomDoze
head https://github.com/SOVIET-ANDROID/device_xiaomi_raphael/tree/0043984637fa5ee28bc4f9d8d03338af28f14bdb

Squashed commit of the following:

commit eb04977d2953642f5910682facdaa12ff653bd93
Author: Adhitya Mohan <me@adhityamohan.in>
Date:   Fri Oct 9 13:35:07 2020 +0530

    raphael: Rename doze target
    * To prevent conflicts with other trees

commit 0de0876159d28e2f41a1642dc752b757bd05e82e
Author: Josh Chasky <jchasky@gmail.com>
Date:   Sat Aug 29 12:35:53 2020 -0400

    Correct doze typos

commit a8e434ad0190ac633ced5aede32766890c8185f7
Author: Alex <du.alexcruz@gmail.com>
Date:   Sat Feb 15 04:17:15 2020 -0500

    Preference category: Match system theme

    Change-Id: Iae433d01b9cbd25d68b0e6a97580e2fd2cac54a3

commit 4125620b295831552736e5ed9891dccf28970d5e
Author: Alex <du.alexcruz@gmail.com>
Date:   Thu Jan 16 21:44:52 2020 -0500

    Themes: Match custom options navbar with Settings

    Change-Id: Ic684444c791a55b27832eb8b4d5ff84f4c8fe15b

commit d45f5ef427efe394d496286ef5f80b82bd4cccad
Author: Alex <du.alexcruz@gmail.com>
Date:   Mon Jan 13 01:17:36 2020 -0500

    Doze: Update DozeSettings to AndroidX

    Change-Id: I9e38f3a6b099a4d4304f1612790238f0d564345f

commit ce5429de9583285a78542fb792c36889f2ad0efe
Author: Alex <du.alexcruz@gmail.com>
Date:   Sun Jan 12 23:15:28 2020 -0500

    CustomDoze: Change strings to match with Settings

    Change-Id: I1e47baf929fddf1fbb822e58434d0bcb8f0f1687

commit 749b6266a5be515aba7f579a700062552ca90003
Author: Alex Koskovich <zvnexus@outlook.com>
Date:   Wed Jan 15 19:30:06 2020 -0500

    Migrate to blueprint where applicable

    Change-Id: I898bc634e01d2ed6f133830762188e2fa6611978

commit e9ef7267ffc7e726c1384907830ce8c2095e2704
Author: Alex Koskovich <zvnexus@outlook.com>
Date:   Wed Oct 16 06:42:49 2019 -0400

    doze: Change name to CustomDoze

    Change-Id: I87d9f69175e35b4ac209f24eae7c9cdc9e62c46c

commit 9ebb99324f6a3b8a41f5b82460f01082e9a78fa7
Author: Anton Hansson <hansson@google.com>
Date:   Tue Aug 14 10:19:34 2018 -0400

    doze: Set LOCAL_SDK_VERSION where possible

    This change sets LOCAL_SDK_VERSION for all packages where
    this is possible without breaking the build, and
    LOCAL_PRIVATE_PLATFORM_APIS := true otherwise.

    Setting one of these two will be made required soon, and this
    is a change in preparation for that. Not setting LOCAL_SDK_VERSION
    makes the app implicitly depend on the bootclasspath, which is
    often not required. This change effectively makes depending on
    private apis opt-in rather than opt-out.

    Test: make relevant packages
    Bug: 73535841

    Change-Id: Ic906adbd670c4dbfe2cdf0b71cdbeaf9ac08a27e

commit 8457bd256da45c93d979018fcc2ba8a1d06b65b9
Author: Alex <alex@dirtyunicorns.com>
Date:   Sun Jul 1 08:50:02 2018 -0500

    doze: Respect RTL

    - Add in a few null checks to prevent possible NPE's.
    - Add missing INTERACT_ACROSS_USERS permission.

    Change-Id: I4c4daf928f3298409d96309d86a333a222ad111f

commit d450b4b008199e55f397fb9b81478a3f0a5f02a8
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Thu Jun 14 09:06:27 2018 -0400

    doze: Use ExecutorService to handle sensor listener

    Maybe this is useless, but out of curiosity let's try what Google
    did for SystemuUI here:
    ezio84/abc_frameworks_base@fabc743

    Registering a sensor seems to be an expensive operation, and we do it on each
    screen-on event, so moving it to an asynchronous task looks like
    a good idea anyway.

    The interesting part about ExecutorService api:
    By
    moving all non-essential binder calls of the main thread or to the
    next frame, we bring this down to 5ms, such that window animation
    and Keyguard animation starts about at the same time.
    https://developer.android.com/reference/java/util/concurrent/ExecutorService
    Change-Id: Id33a200b68e2f313af4258c6109c7b80aa93329c

    Change-Id: I1b38dbf9091ff056fad3e0e43a4232f8deadc7c7

commit 6bc5fd608267935b1bb92021827822380c438396
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Wed May 23 05:49:58 2018 -0400

    doze: Fix CustomDoze receiver protected broadcast logspam

    05-23 10:32:55.236   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
    05-23 10:32:55.236   834 13503 E ActivityManager: java.lang.Throwable
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19603)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)
    05-23 10:32:55.243   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
    05-23 10:32:55.243   834 13503 E ActivityManager: java.lang.Throwable
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19696)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)

    Change-Id: I132298a7acf246b8153019ce5a3f4129d9eeca4b

commit c5eb54f4ce19ef9c976b07f3c56064134198f765
Author: ezio84 <brabus84@gmail.com>
Date:   Thu May 17 15:34:28 2018 +0200

    doze: Custom Doze service improvements

    Don't start the service when all options are disabled or just
    pulse on notification is enabled.

    Start the service when enabling options only if it's not already running.

    Change-Id: I07dab2e38b6701669dfe07d7154716de4b781609

commit 786c9fe9f9aaa399ea6af34646e6cec65e696f30
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Sat May 12 18:57:43 2018 -0400

    doze: Allow to enable Doze proximity actions without the notifications one

    Change-Id: Iacb5573c3b66d2e33c67dbf9ddbedc66b7ffaef0

commit 22d2b807155265d5ba92024597ce472ebc07532d
Author: Alex Koskovich <zvnexus@outlook.com>
Date:   Wed Oct 16 15:45:15 2019 -0400

    doze: Change SDK to 29

    Change-Id: Ibea87317edb015e4ecd763d03797e112f39ee44a

commit 06c1b625a329908680bf39e2e31cdd06b2ef7e52
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Sat Jan 6 01:21:06 2018 -0500

    doze: Change SDK to 27

    This not only gets us inline with other packages we compile but fixes a
    weird theme issue in that the navbar was black on black, black icons on
    a black bar. We could of gone about this a different way by defining the
    theme and calling it from the manifest but this is just easier :-)

    Change-Id: I1fd191fe6991071bdfa278c704074b28c11cf1c1

commit b7a827a6e965c312d404bd3b56f18585db55c3b8
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Mon Nov 6 16:45:01 2017 -0500

    doze: Remove Doze dialog

    We don't need this, nobody does. Most users are aware of ambient display and
    what is capable of.

    Change-Id: I30abd53cfae1101157b92bf9b869e6469915c2f2

commit 54f9a5f8727c63b7d71f8094eb043ac58f7443da
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Mon Nov 6 15:57:56 2017 -0500

    doze: Change package name for uniformity

    With Android O we want to stick to just one package name for device specific doze.

    - Set Doze package to compile.
    - Enable bool to hide AOSP ambient display options.

    Change-Id: I3279d0d3d06141f282a1135c9fb95f25e2fc994b

commit da61219bc2cc8a4704c56bdb1d2aaf591f943fbb
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Sun May 21 22:51:19 2017 +0200

    doze: Further Refactoring, change theme to match Pixel

    - Remove package from showing up in settings.

    - Changed package name so we can do our own thing and not have it
    get in the way of the Doze package currently used by Nick and others.

    Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6999ac

commit ee60424c1c5dce938d797fcfd4b7587d78da3ff7
Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
Date:   Sun Aug 21 08:47:12 2016 +0100

    doze: Clean up doze

    * Remove always enabled option.
    * Use stock fade in delay.

    Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6771ac

commit 12703fc1d252fd8b69664a3c1c0b84954b0b66d2
Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
Date:   Sun Apr 24 23:01:57 2016 +0100

    doze: Doze improvements

    * restructure the app
    * add a tilt sensor from hammerhead-caf with an option to enable/disable
    * add a one time dialog on first start to help users understand how the app works
    * remove proximity wake up option and add an option to enable the sensors as soon as the screen turns off
    * adjust and add new doze configs

    Change-Id: Ia9d9a807d6c4f1a80a2ba8780e7486560f9a1d87

commit 2bad69e3effffb024d6168cfbd5718eeb945b518
Author: Patrick Lower <devvortex@gmail.com>
Date:   Sun May 21 21:47:48 2017 +0200

    doze: Refactoring for the Xiaomi devices

    Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f9e9de0f

commit 6c959222df21c39b487f10257211216e9d38deb1
Author: TheStrix <parthbhatia98@gmail.com>
Date:   Sun May 21 21:35:45 2017 +0200

    doze: Remove summary for Doze

    * Doesn't look good.

    Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f8

commit af66e4204a17695ca9f128809b76be053e5390bb
Author: Michael Bestas <mikeioannina@gmail.com>
Date:   Tue Dec 1 16:24:07 2015 -0600

    doze: ScreenType utility from CM SDK

    Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f1e6de0f

commit ad0274724757a480a0428f7f1beffdca8c40c970
Author: Dave Daynard <nardholio@gmail.com>
Date:   Tue Sep 8 22:56:10 2015 -0400

    doze: Fix typo

    Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9

commit 5c27c6ffe9734f55f45f91b2393d2dc2c970687b
Author: Patrick Lower <devvortex@gmail.com>
Date:   Wed Aug 5 10:51:03 2015 -0400

    doze: Properly fix future timestamp error

    Previously attempted fix at review.cyanogenmod.org/#/c/104083/
    The timestamp isn't in the future, that would be impossible.
    The real issue is the timestamp from the SensorEvent is a true
    timestamp, the System.nanoTime is nanoseconds since boot.
    So the previous patch would always return false and never pulse.
    I've simply changed it so that the wakeup call gets sent the current
    System.nanoTime in milliseconds since boot so it does not think the
    event came from the future since the wakeUp method expects
    uptimeMillis, not true world time.

    Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294

commit 880949733a3f94c01cff5ae7671220a3d843e7d6
Author: Brandon McAnsh <brandon.mcansh@gmail.com>
Date:   Fri Jul 24 15:40:45 2015 -0400

    doze: Prevent a PM wakeup with a timestamp in the future

    Prevents:

    java.lang.IllegalArgumentException: event time must not be in the future
    at android.os.Parcel.readException(Parcel.java:1550)
            at android.os.Parcel.readException(Parcel.java:1499)
            at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
            at android.os.PowerManager.wakeUp(PowerManager.java:666)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
            at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

    Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
    Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>

commit 368b50b273867373e76d8f62410cb4d6819f06d6
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat Jul 4 13:44:53 2015 -0400

    doze: Restore proximity wake preference on boot

    Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1

commit a2b79dab55e8f760b551d145cd89291bd1e5b8f7
Author: Dave Daynard <nardholio@gmail.com>
Date:   Mon May 25 12:54:00 2015 -0400

    doze: Add proximity wake

    Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b

commit d1eaec1e9876442f178f5583404fe30951f06b80
Author: luca020400 <luca.stefani.ge1@gmail.com>
Date:   Sun May 24 15:47:17 2015 -0700

    doze: Add back button to action bar

    Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9

commit 1962f5738edd83a87e197cb60fa67e6d46ca44a4
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat May 23 18:29:13 2015 -0400

    doze: Fix defaults

    Change all defaults to false.

    Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8

commit ebad6462f6d1ed9f537a54945e2924eb9f01e3c5
Author: Christopher R. Palmer <crpalmer@gmail.com>
Date:   Sat May 23 11:42:49 2015 -0700

    doze: Consolidate Doze settings

    * Allow user to disable ambient display from gesture panel
    * Disable/enable doze settings based on ambient display state

    Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c

commit c4ea4961054a59b380f293d525ef7d05a76a52e2
Author: Arne Coucheron <arco68@gmail.com>
Date:   Wed May 20 00:56:19 2015 +0200

    Doze: Set gesture to disabled by default

    Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5

commit 25bf27f854c0671f31ac2f93809968c30261256e
Author: Patrick Lower <devvortex@gmail.com>
Date:   Mon May 11 16:14:17 2015 -0400

    doze: Add service for using proximity sensor for wake-up

    * Added custom service that uses proximity sensor in wake-up mode
      to trigger display on.
    * If more sensor triggers are suitable to use, they can be added
      to the service.

    Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48